functions.php, inc/wpautop.php
Disable the wpautop filter. This is a preliminary fix that will need to be revisited when we work on the Gutenberg editor. Gutenberg automatically disables wpauto when an HTML Block is being rendered, but wpautop may still be useful in other visual editing contexts.
=> Disable wpautop

asu-navigation-menu.php
A few changes that clean up the code and prevent the main navigation menu from closing before it has rendered all menu items properly:
* Removed a closing `<div>` tag (line 66) that was the main culprit of the odd behavior we were seeing. This tag was attempting to close multi-level menu `<div>`s that were already being properly closed on line 55. The end result was that it closed the actual `navbar-nav` element after the first time we rendered a multi-level drop-down. This led to all subsequent top-level menu items existing outside the `navbar-nav`, where they picked up some flex-box styling from the parent `<div>` that spread them out across the screen.
* Removed the `echo` statement on line 67: we had already cleared out the `$column` variable at this point, meaning all we were …
=> Fix Navbar Closing Too Early

acf-json/group_5ef954da477f5.json, hero.php
Add the ability for users to select a highlight style for the hero image title text:
* Added a new field to the existing ACF field group that allows the user to select "gold", "black", or "none" as a text highlight for hero images
* Added corresponding code in the `hero.php` template partial to implement the new option.
* Cleaned up the existing `hero.php` to remove some unnecessary CSS classes, and some inline CSS that would conflict with our current plans to limit hero images to a maximum of 1920px
=> Add Highlight Options to Hero Title

footer.php, header.php, inc/acf/includes/json.php, inc/advanced-custom-fields.php
The use of `get_stylesheet` functions in various parts of the parent theme will fail when in the presence of a child theme. These are a set of corrections that should force the parent theme to look within ONLY the parent theme for the various called resources.
=> Child theme compatibility - get_template_directory vs get_stylesheet_directory

.travis.yml
Builds are failing on certain (older) versions of PHP during our Travis CI testing. This addition to the `travis.yml` file will prevent Travis from automatically updating to Composer 2.0 when it creates our test environments.
This fixes #32
=> Prevent Travis from Updating Composer

.travis.yml, README.md
Resolves #34 
An initial restructuring of the `readme.md` file focusing on creating an overall structure with two main areas: one for end users, and one for developers/contributors. This is just a first step towards a new readme, but I wanted to get it folded into develop so that others could start contributing.
- Contains a proposed structure for the file
- Functional table of contents with working links
- Some previous content left in place for review
I am having it 'resolve' #34 as that issue was a test issue Bryan created, and so we can create a batch of new tasks in the documentation project for the readme.
=> Initial Readme Structure

searchform.php
I noticed that the bootstrap class "bg-transparent" was added to the search button which gives it a transparent background. 
I only removed the class from there so that when we add a background to the 404 page, the search bar will be displayed all as one bar including the search button, instead of having the search button looks separate when the transparent background is applied.
=> Deleted bg-transparent class from the search button

acf-json/group_60074496e95ba.json, templates-global/hero.php, templates-loop/content-single.php
I noticed that we need to have the option to hide page title in case if page title has to be styled like the ones in Devils drop off website.
I had to remove the page title and add a regular Heading block to create a styled title. But the issue was that the pages would show with no title in the editor, and we can't tell which is which: 
To solve this issue:
- I created a True/False field in ACF.
- Added an if condition before printing the page title in **hero.php** template and **content-single.php**. 
- This feature will be added to post and page types.
=> Added a checkbox to have the option to hide page title

inc/render-partials.php
Fixes #80. 
A one-line fix within `render-partials.php` addressed the breakpoint at which the word "Home" appears in the mobile menu. Recommended fix from UDS-332 from the unity project. https://github.com/ASU/asu-unity-stack/pull/96
=> Adjust display none property of the "home" text in the mobile menu.

inc/enqueue.php
I added uds_wp_gutenberg_css function to enqueue **theme.css** in editor area, this will load theme styles in admin side to show the real style of gutenberg blocks in the editor area.
=> Enqueued theme.css to load in editor area only

header.php
Replacing two placeholder links in `header.php` that were just links to the top of the page. Suggested changes are:
* Update the main ASU logo in the header to link to 'https://www.asu.edu'
* Update the 'Sign In' link in the global menu bar to link to 'https://my.asu.edu'
We have been asked if the 'Sign In' link could also pass users through to the WordPress site, but that will require some investigation. This fix at least means that an unauthorized user who clicks on 'Sign In' will be logged in to their ASU account via CAS - which is the real purpose of that link.
=> Replace Dummy Links in Header

.gitignore, browserSyncOptions.json, gulpconfig.json, gulpfile.js, package.json
I updated the gulpfile.js file, added .**pipe(browserSync.reload({ stream: true }))** to end of each: 
**minifycss** and **scripts** tasks to make the live stream work when changes are made.
- This will allow us to view changes right after we save the sass file as shown in the video bellow:
https://user-images.githubusercontent.com/15880606/110175609-4da7cc00-7dbf-11eb-9638-bfc8c1e3e249.mov
=> Gulp browserSync function

README.md, browserSyncOptions.json
I deleted the browserSyncOptions.json file to prevent it from being tracked by git, it was added to gitignore previously. 
I also updated the readme file, added a new step to create browserSyncOptions.json file and put your browser sync options in there. 
Files I changed: 
- Deleted browserSyncOptions.json. 
- Updated README.md
=> Deleted browserSyncOptions.json file

inc/scroll-to-div.php
I updated the jq code to fix the issue with anchor links on tabs and accordion. 
added the line to if statement: 
`(0 != target.offset().top)`
=> Fix anchor issues with tabs and accordion

acf-json/group_602edd7eb0e61.json, templates-blocks/cards/card.php
Resolves #162 
Images on cards still had a hard-coded placeholder for the `alt` tag, so we needed to retrieve that value and add it to the markup.
Changes proposed in this pull request:
- Change the 'image' field in the ACF group to return an array of data, and not just the image URL
- Update the code to retrieve both the image URL and the `alt` text from that array, and use those values when building card images.
=> Add Alt Tag to Card Images

js/hero_video.js
updated hero_video.js to only run when there is a video to avoid getting the error: 
`'Uncaught TypeError: Cannot read property 'addEventListener' of null'`
=> Fix addEventListener of null error on video hero

inc/customizer/customizer-settings.php, inc/render-partials.php, inc/theme-settings.php, js/customizer-controls.js
Our current customizer and footer code simply repeats the site name beneath the logo in the ASU global footer. This was based on existing XD/Storybook examples, and is probably the 'correct' thing, but does not allow for the customization that our clients need. This PR updates both the Customizer and our footer code to allow for customized text in the footer.
**Changes proposed in this pull request:**
- Add two new settings for the Customizer:
- `footer_unit_name_type`: for storing the choice between using the unit name, or custom text
- `footer_unit_name_text`: for storing the custom text
- Add a new control in the Customizer to allow users to choose between repeating the site name, or entering customized text, for the footer text just below the logo
- Add a new control, hidden by …
=> Allow Customized Unit Name Text in Footer

templates-blocks/blockquote/blockquote.php, templates-blocks/button/button.php, templates-blocks/cards/card.php, templates-blocks/content-sections/image-overlap.php, templates-blocks/overlay-card/overlay-card.php
Some of our ACF blocks were throwing warnings about uninitialized variables with regard to retrieving the additional CSS classes from the `advanced` area of the Gutenberg editor. It turns out that I had copied/pasted the wrong bit of code to multiple blocks and left out the line that was initializing the variable used to hold those additional class names.
The following blocks were updated with this new code:
- Blockquote
- Button
- Card
- Content/Image Overlap
- Program (aka 'overlay') Cards
This was a code-only change, and **does not** require any re-syncing of  ACF field information. Changes proposed in this pull request:
- Update the code in all blocks that were not up to date already. The new code not only initializes the variable, but also includes sanitizing the input, and trimming …
=> Fix PHP Warnings on Additional Classes

inc/uds-blocks.php
Adds a function to the `functions.php` stack to automatically sync any changes to the ACF local JSON files with the database. Works automatically behind the scenes upon anyone hitting any admin screen. (Activated with the `admin_init` hook.) 
Can't take the credit here. :-) This was courtesy of the Delicious Brains dev crew and was mentioned in a recent blog post.
- https://deliciousbrains.com/advanced-custom-fields-wordpress/, under the header Using the Local JSON feature.
- https://gist.github.com/polevaultweb/32056461d1e4b85426211d2e5f85a3eb, provided code example from the blog.
Testable using the following procedure.
- Temporarily remove all JSON files from `/acf-json`. 
- Log into the admin screen and trash all entries in `wp-admin/edit.php?post_type=acf-field-group`
- Empty the …
=> Automatically sync ACF JSON files upon hitting the admin screen.

templates-global/hero.php
Resolves #200 
A malformed URL `target` attribute is causing all Hero buttons created with our ACF loop field to open in new tabs, regardless of whether or not the user requested it. All buttons have code that looks like `target="%s"` because of an error in my `sprintf()` syntax - I put a `%` where a `$` should have gone.
Recent rounds of QA on our sites also indicated that we were not properly honoring the _open in new tab_ or _external link_ options on these hero buttons. While the user could select those options, we were not properly applying those settings.
Changes proposed are:
- Fix the `sprintf()` bug by replacing the `%` in the `target` placeholder with a `$`, and use the correct variable
- Add code to read our Button component's 'external link' button and apply `rel="noopener …
=> Fix Hero Button Attributes and Add Support for 'target' and 'rel'

acf-json/group_602edd7eb0e61.json
Resolves #157
Changes to both fix a potential issue when editing card body (the interface to create links was not working consistently), and to bring the cards in line with the UDS standards. As I understand it from the XD, links should not be embedded in the actual body text of a card; they are limited to the links area of the card, and are considered calls to action (like buttons).
Changes suggested in this request:
* Updated the Card fields to use our 'minimal' toolbar, which does not contain a button for creating links. For most users, then, we are solving both the original issue and keeping them in line with the standards.
* Add the 'text' version of the toolbar, which has more options, for power users who may need more flexibility if non-standard designs are approved.
=> Updated WYSIWYG Settings on Card Body

inc/render-partials.php
I needed to override one of the theme functions in the child theme but was unable to do so for no `function_exists` checking has been done.
I added the line  `if ( ! function_exists( 'uds_wp_render_contribute_button' ) ) {` 
to check the function `uds_wp_render_contribute_button()`
=> contribute_button

templates-blocks/cards/card.php
Switched from `wp_kses()` to `wp_kses_post()` to allow for more HTML characters/elements to appear in our cards. This arose when we needed to use certain tags, such as `<sup>` and `<sub>`, and HTML entities like `&trade;` and `&copy;` in certain cards.
The previous code was using `wp_kses()` without any allowed tags, which was a bit too restrictive for our needs. By switching to `wp_kses_post()`, we end up allowing the tags that WordPress has deemed acceptable for standard post content - which seems like a more reasonable stance to take.
=> Allow for More HTML Characters in Card Body

inc/setup.php, inc/widgets.php
To **temporarily** prevent the odd redirects we've been encountering when attempting to open the widget screen, this simple update removes support for the new block-based widget editor, therefore falling back to the traditional widget editor.
Changes in this PR:
- Added code to remove support for the block-based editor in `inc\setup.php`
- removed that same existing code from `inc/widgets.php`, as it didn't seem to be working when placed there
This PR is just fix the fact that you can't add widgets at all in v5.8 of WordPress, and we should fix this more completely when time allows. I'm still unsure about what, exactly, is causing the problem. Google searching points towards TinyMCE (used in the only widget we provide), but removing that particular widget (or trying a simple text input) …
=> Remove Support for Block Widget Editor

templates-blocks/cards/card.php
When we switched to using the ACF Pro WYSIWYG editor for card titles, and allowed for additional special characters in the body text, we introduced additional paragraph tags in both the title and body where we didn't want them.
A basic card title should be created like this: `<h2>Title text here</h2>`
But the WYSIWYG editor was adding paragraphs around the content like this: `<h2><p>Title text here</p></h2>`
We were also seeing extra `<p>` tags in the body content, sometimes more than one, causing some non-standard spacing between title and body text.
Changes proposed in this PR:
- Use the additional formatting argument when retrieving the ACF values for title and body text. By passing `false` as the argument, ACF will not include the extra formatting (the `<p>` tags) when retrieving the …
=> Remove Unwanted Pagragraph Tags in Cards

header.php
We recently updated our theme to have the global 'Sign In' and 'Sign Out' links point to the local WordPress admin (/wp-admin) instead of my.asu.edu, but didn't realize that we need to prevent Google from trying to follow those links and sign in to our sites.
Not only is this a possible security issue, but signing in fires off a string of redirects - first within WordPress, then to ASU's SSO, then back - that cause errors in Google Search Console.
Changes suggested in this PR:
- Add "rel=nofollow" to both links to prevent Google from following them
=> Prevent Google from crawling our Sign In and Sign Out Links

inc/analytics/asu-gtm-analytics-tracking-code.php, inc/analytics/google-tag-manager-noscript-code.php
GTM iframe fix accessibility errors - title attribute for compliance, aria-hidden so screen-readers ignore the element.
=> gtm iframe a11y fixes

js/tabbed-panels.js
While working on some preliminary pattern library stuff, I noticed two things:
1. I was consistently seeing ` undefined is not an object (evaluating '$( '.nav.nav-tabs' )[0].scrollWidth')` in the Javascript console. This was always showing up in the editor, and on the front-end in certain situations. It was caused by the difference in the structure of tabs on the front end and in the editor.
2. We could not longer click the 'Browse All' button in the modal block inserter  (shown in image below) to open the full block inserter. Clicking that button would do nothing. This was caused by a function we had in place to prevent the unwanted following of certain clicks in the editor. That method was swallowing up the click on the 'Browse All' button.
1. Wrap the attempt to access the first child …
=> Fix JS Console Notice and Restore Block Inserter Functionality

header.php, inc/customizer/customizer-settings.php
In order to add a website to Google Search Console, we must prove we own the site: https://support.google.com/webmasters/answer/9008080?hl=en#meta_tag_verification
This PR adds a new Customizer field in the ASU Analytics section to set the ownership verification id.
1. Choose the HTML tag method on the [Ownership verification page](https://search.google.com/search-console/ownership) for your property.
2. Copy the "content" value from the provided HTML snippet in the Search Console verification wizard:
```
<meta name="google-site-verification" content="COPY_PASTE_THIS_VALUE" />
```
3. Paste into Customizer field:
=> Add Customizer field for Google Search Console ownership verification

README.md, package-lock.json, package.json
volta pin node & npm, de-version gulp-imagemin to solve ES6 compile issue, readme update browsersync
- Readme: Clarify how browser-sync works on local machine
- `volta pin node & npm` at fixed versions, now devs will always be on same tooling versions
-  `gulp-imagemin@8` fails on `gulp watch-bs` :
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/jkcox1/local-sites/unity-blocks-dec22/wp-content/themes/UDS-WordPress-Theme/node_modules/gulp-imagemin/index.js
require() of ES modules is not supported.
require() of /Users/jkcox1/local-sites/unity-blocks-dec22/wp-content/themes/UDS-WordPress-Theme/node_modules/gulp-imagemin/index.js from /Users/jkcox1/local-sites/unity-blocks-dec22/wp-content/themes/UDS-WordPress-Theme/gulpfile.js is an ES module file as it is a .js file …
```
=> volta pin node & npm, de-version gulp-imagemin, readme update

inc/extras.php
Added to `<head>` and set loading order as recommended by Google documentation, confirmed asu.edu is doing the same sequence: 
- Load gtag.js
- window.dataLayer init
- dataLayer.push
=> add dataLayer init script

inc/header-localizer-script.php, inc/hooks.php
Subscribers on RTO need to be redirected to the page they logged in on. 
Might be useful for site editors as well.
1. User visits page
2. User clicks login > query param passed to CAS
3. CAS login > user redirected to wp-admin
4. `admin_init` runs to check if query param exists
5. redirect user if necessary
=> redirect to previous page after CAS login

inc/enqueue.php
There was no PR or code history for removing `lodash` from v0.56, unfortunately this got overwritten between v0.56 and v0.57 in error.
The theme works on WP Engine without this enqueuing update. Local development on Lando is broken.
=> enqueue lodash with admin script

inc/class-unity-react-header-navtree-walker.php, inc/header-localizer-script.php
Header menu would output "0" string when an empty menu with no menu items was set as the main menu. After trial and error it was not an issue with menu items, but the CTA button array.
- `isset` check on walker args, fixes PHP warning user sees `Attempt to read property "has_children" on null`
- set CTA array to null, fixes "0" string output 
- if there are only CTA buttons, set menu items to null. Otherwise home icon is output, and breaks UDS styling. Button should be vertically centered with site title, unless menu items exist, it will snap down to the menu items row.
=> Fix errors and bugs when no menu items
